### ISSUE TITLE
V2.2.0 doesn't work, 2.1.2 works

### ISSUE THREAD

**Issue by sumirecccp** [iamscottxu/obs-rtspserver#105]
Hello,
I tested v2.2.0 and found that it's unable to play stream from either intranet or internet. Tested on my smartphone & vps.(192.168.1.x:aaaa/live) On localhost PC it works(localhost:aaaa/live). No matter multicast enabled/disabled. Backroll to 2.1.2 and all go well.

**Comment by TuKerMaN** [comment]
Can confirm this is happening to me since RC1 in Win10 21H2 1526.

- Tried with integrated H264 AMF and software x264 encoder (OBS 27.0.0 and 27.2.0).
- Also with this one: https://github.com/e00E/obs-amf v0.1.0.
- Firewall disabled.
- Confirmed with netstat that plugin binds and listens to 127.0.0.1 and local interface IPs (IPv4 and IPv6 for both cases).
- Tried using several ports, low and high, with / without admin elevation.
- Can stablish connection (via telnet), but dont get any response after sending standard RTSP header
- Used several clients (VLC, local camera DVR, several Android apps) with the same result. Usually they can connect but get a black stream.

In logs, v2.2.0 seems to always open a multicast IP and port, even with multicast setting disabled. Don't know if that affects in any way
[VLC_client_rtsp_2.1.2.log](https://github.com/iamscottxu/obs-rtspserver/files/8111288/VLC_client_rtsp_2.1.2.log)
[OBS_rtspserver_2.2.0.txt](https://github.com/iamscottxu/obs-rtspserver/files/8111290/OBS_rtspserver_2.2.0.txt)
[VLC_client_rtsp_2.2.0.log](https://github.com/iamscottxu/obs-rtspserver/files/8111291/VLC_client_rtsp_2.2.0.log)
[OBS_rtspserver_2.1.2.txt](https://github.com/iamscottxu/obs-rtspserver/files/8111292/OBS_rtspserver_2.1.2.txt)
