### ISSUE TITLE
Failed to start output (Error)

### ISSUE THREAD

**Issue by dimdallas** [iamscottxu/obs-rtspserver#3]
Hello @iamscottxu 

I work on Windows 10 and have installed your plug-in via the .exe file.
I also use a open source RTSP server (recommended by ffmpeg) from here: https://github.com/revmischa/rtsp-server
My OBS sources are either a Text (GDI+) or a Video Capture Device taking input from my HTC Vive camera.
I go to Tools -> RTSP Server, I give port :5545 (according to my server) but when I press Start, it gives me the error "Failed to start output".
I can't find anything related in the File -> Settings -> Output.
I hope you can help me with this.

Thanks in advance,
Dimitris

**Comment by iamscottxu** [comment]
There are many reasons for the error "Failed to start output". 
Please provide OBS log file, log file can help me understand the cause of the error.
You may need to check your OBS output configuration. For example, you may have used the wrong video encoder.

**Comment by samliddicott** [comment]
In my case, the logs error was:
**14:23:58.512: can't begin data capture**
corresponding to the UI error shown: Failed to start output

The full logs are:

14:23:37.545: CPU Name: Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz
14:23:37.545: CPU Speed: 2295MHz
14:23:37.545: Physical Cores: 4, Logical Cores: 8
14:23:37.545: Physical Memory: 16286MB Total, 8445MB Free
14:23:37.545: Windows Version: 10.0 Build 19042 (release: 2009; revision: 685; 64-bit)
14:23:37.545: Running as administrator: false
14:23:37.545: Aero is Enabled (Aero is always on for windows 8 and above)
14:23:37.546: Windows 10 Gaming Features:
14:23:37.546: 	Game DVR: On
14:23:37.547: Sec. Software Status:
14:23:37.548: 	Microsoft Defender Antivirus: enabled (AV)
14:23:37.549: 	Windows Firewall: enabled (FW)
14:23:37.550: Current Date/Time: 2020-12-19, 14:23:37
14:23:37.550: Browser Hardware Acceleration: true
14:23:37.550: Portable mode: false
14:23:37.786: OBS 26.1.0 (64-bit, windows)
14:23:37.786: ---------------------------------
14:23:37.840: ---------------------------------
14:23:37.840: audio settings reset:
14:23:37.840: 	samples per sec: 48000
14:23:37.840: 	speakers:        2
14:23:37.841: ---------------------------------
14:23:37.841: Initializing D3D11...
14:23:37.841: Available Video Adapters: 
14:23:37.848: 	Adapter 0: NVIDIA Quadro K1100M
14:23:37.848: 	  Dedicated VRAM: 2107179008
14:23:37.848: 	  Shared VRAM:    4244094976
14:23:37.848: 	  PCI ID:         10de:ff6
14:23:37.849: 	  Driver Version: 25.21.14.2545
14:23:37.849: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=
14:23:37.849: 	Adapter 1: Intel(R) HD Graphics 4600
14:23:37.849: 	  Dedicated VRAM: 117964800
14:23:37.849: 	  Shared VRAM:    2147483648
14:23:37.849: 	  PCI ID:         8086:416
14:23:37.849: 	  Driver Version: 20.19.15.5058
14:23:37.856: Loading up D3D11 on adapter NVIDIA Quadro K1100M (0)
14:23:37.911: D3D11 loaded successfully, feature level used: b000
14:23:37.911: DXGI increase maximum frame latency success
14:23:37.911: D3D11 GPU priority setup failed (not admin?)
14:23:38.410: ---------------------------------
14:23:38.410: video settings reset:
14:23:38.410: 	base resolution:   1536x864
14:23:38.410: 	output resolution: 1280x720
14:23:38.410: 	downscale filter:  Bicubic
14:23:38.410: 	fps:               30/1
14:23:38.410: 	format:            NV12
14:23:38.410: 	YUV mode:          709/Partial
14:23:38.410: NV12 texture support enabled
14:23:38.412: Audio monitoring device:
14:23:38.412: 	name: Speakers / Headphones (Realtek High Definition Audio)
14:23:38.412: 	id: {0.0.0.00000000}.{b07855f5-f1a6-4339-bf8d-6398d44be84d}
14:23:38.415: ---------------------------------
14:23:38.417: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
14:23:38.418: Failed to load 'en-US' text for module: 'decklink-captions.dll'
14:23:38.419: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
14:23:38.450: [AMF] Unable to load 'amfrt64.dll', error code 126.
14:23:38.453: [AMF] AMF Test failed due to one or more errors.
14:23:38.453: Failed to initialize module 'enc-amf.dll'
14:23:38.476: [obs-browser]: Version 2.9.1
14:23:38.476: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
14:23:38.479: NVENC supported
14:23:38.493: Signal declaration 'start' exists
14:23:38.493: Signal declaration 'stop' exists
14:23:38.493: Signal declaration 'pause' exists
14:23:38.493: Signal declaration 'unpause' exists
14:23:38.493: Errors/warnings for 'void error(char* msg)':
14:23:38.493: 
14:23:38.493: declaration (1, 12): Expected 'type'
14:23:38.493: 
14:23:38.493: Signal declaration invalid: void error(char* msg)
14:23:38.505: Couldn't find VLC installation, VLC video source disabled
14:23:38.510: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
14:23:38.511: No blackmagic support
14:23:38.515: ---------------------------------
14:23:38.515:   Loaded Modules:
14:23:38.515:     win-wasapi.dll
14:23:38.515:     win-mf.dll
14:23:38.515:     win-dshow.dll
14:23:38.515:     win-decklink.dll
14:23:38.515:     win-capture.dll
14:23:38.515:     vlc-video.dll
14:23:38.515:     text-freetype2.dll
14:23:38.515:     rtmp-services.dll
14:23:38.515:     obs-x264.dll
14:23:38.515:     obs-vst.dll
14:23:38.515:     obs-virtualoutput.dll
14:23:38.515:     obs-transitions.dll
14:23:38.515:     obs-text.dll
14:23:38.515:     obs-rtspserver.dll
14:23:38.515:     obs-qsv11.dll
14:23:38.515:     obs-outputs.dll
14:23:38.515:     obs-filters.dll
14:23:38.515:     obs-ffmpeg.dll
14:23:38.515:     obs-browser.dll
14:23:38.515:     image-source.dll
14:23:38.515:     frontend-tools.dll
14:23:38.515:     enc-amf.dll
14:23:38.515:     decklink-ouput-ui.dll
14:23:38.515:     decklink-captions.dll
14:23:38.515:     coreaudio-encoder.dll
14:23:38.515: ---------------------------------
14:23:38.515: ==== Startup complete ===============================================
14:23:38.523: All scene data cleared
14:23:38.523: ------------------------------------------------
14:23:38.586: WASAPI: Device 'Speakers / Headphones (Realtek High Definition Audio)' [48000 Hz] initialized
14:23:38.586: [Loaded global audio device]: 'Desktop Audio'
14:23:38.657: WASAPI: Device 'Microphone (Realtek High Definition Audio)' [48000 Hz] initialized
14:23:38.657: [Loaded global audio device]: 'Mic/Aux'
14:23:38.667: warning: deprecated pixel format used, make sure you did set range correctly
14:23:38.688: [Media Source 'video-clip']: settings:
14:23:38.688: 	input:                   C:/Users/sam/Desktop/Christmas-2.mp4
14:23:38.688: 	input_format:            (null)
14:23:38.688: 	speed:                   100
14:23:38.688: 	is_looping:              no
14:23:38.688: 	is_hw_decoding:          yes
14:23:38.688: 	is_clear_on_media_end:   yes
14:23:38.688: 	restart_on_activate:     yes
14:23:38.688: 	close_when_inactive:     no
14:23:38.688: Switched to scene 'Scene'
14:23:38.688: ------------------------------------------------
14:23:38.688: Loaded scenes:
14:23:38.688: - scene 'Nothing':
14:23:38.688: - scene 'Scene':
14:23:38.688:     - source: 'Christmas scene' (image_source)
14:23:38.688:     - source: 'Video Capture Device' (dshow_input)
14:23:38.688: - scene 'Scene 2':
14:23:38.688:     - source: 'video-clip' (ffmpeg_source)
14:23:38.688:     - source: 'Video Capture Device' (dshow_input)
14:23:38.688: ------------------------------------------------
14:23:38.700: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
14:23:38.700: 
14:23:38.777: ---------------------------------
14:23:38.777: [DShow Device: 'Video Capture Device'] settings updated: 
14:23:38.777: 	video device: XSplit VCam
14:23:38.777: 	video path: \\?\root#image#0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
14:23:38.777: 	resolution: 1280x720
14:23:38.777: 	flip: 0
14:23:38.777: 	fps: 30.00 (interval: 333333)
14:23:38.777: 	format: ARGB
**14:23:58.512: can't begin data capture**

**Comment by Richard-G4WKW** [comment]
I am new to OBS, but after installing it and your plugin under Windows 10 Pro I initially had a problem with the  "Failed to start output" error.  I noticed that if I X'd out of the dialog box and re-opened it via Tools >> RTSP Server, that it had saved the last changes that I had made to it (i.e. the port number and whether or not Autostart was checked).

I set up my port number (8554) and checked Autostart, then exited OBS and then restarted it.  I had a Windows Security dialog box come up on the restart (presumably to accept using the port, but I did not take real note of it), which I accepted, and when OBS ran and I checked the RTSP Server it was running.  From then on, I have had no problems, I can start and stop the server using the buttons and everything is working.

I thought that I would just post this info as it could help others.

**Comment by tormyvancool** [comment]
to me gave the same. Port 554 on W7: failed. Then I changed to 555 it worked perfectly

**Comment by gretel** [comment]
@iamscottxu on `osx` the application will run a as non-priviliged user. therefore, opening ports below `1024` is not possible. it's working fine using i. e. port `5554`.

my suggestion is to have that as default to prevent confusion. regards

**Comment by iamscottxu** [comment]
> @iamscottxu on `osx` the application will run using a non-priviliged user. therefore, opening ports below `1024` is not possible. it's working fine using i. e. port `5554`.
> 
> my suggestion is to have that as default to prevent confusion. regards

Thanks for your suggestion.
