### ISSUE TITLE
2.02 Stop working, how to restart it

### ISSUE THREAD

**Issue by Barabba11** [iamscottxu/obs-rtspserver#57]
Hi, first let me thank you for this plugin, really useful!
I've just notice the 2.03 is out and I'll test it, anyway this morning I had a trouble, OBS was running from hours and I've opened its rtsp from another PC with VLAN, working, then I've opened with VLAN on an Android TV, it opened, but the second time it didn't more, the connection went in time out. I've stop the plugin but it didn't show me again start, I've closed Obs64.exe, the main window closed but the process still work in taskmanager, i've killed it than and reload obs,
My questions are:
- How can I fix the problem if it happens again? There is any dll running on task man that I can kill instead of obs64?
- May you please introduce a "watchdog" ar something to let plugin recover itself if it "hangs"?
- What you fixed in this new 2.03? There is any changelog?
- may you please withe in the plugin window the actual version? So it will be easy to understand if we need an update, 
thank you a lot!

**Comment by brodi1** [comment]
Hi @Barabba11 !

Does this problem always happen? Will it happen again if you do it again?

Q: > How can I fix the problem if it happens again? There is any dll running on task man that I can kill instead of obs64?
A: Could you maybe send the log file output? (be careful not to publish any sensitive data)

Q: > May you please introduce a "watchdog" ar something to let plugin recover itself if it "hangs"?
A: > Could you explain that in more detail?

Q: > What you fixed in this new 2.03? There is any changelog?
A: > Version 2.0.3 fixed a bug when using NVENC decoder See: https://github.com/iamscottxu/obs-rtspserver/releases/tag/v2.0.3

Q: > may you please withe in the plugin window the actual version? So it will be easy to understand if we need an update,
thank you a lot!
A: Could you explain that in more detail?

**Comment by Barabba11** [comment]
Hi, I couldn't say it yet because I'm not fully testing, before I need to find a way to switch scene by a simple http page, but the script doesn't work (
Anyway I suppose it wil happen, it happened too easy to think it will not happen more. I've just connected 3 times during firsts experiments to make it "hang". I'll report more when I'll test it hugely.
The log output didn't cotain any interesting information, it just hang and since that time all was ok.. or maybe there is your own log file somewhere?

A watchdog is a way to reload if something goes wrong, the idea to introduce something similar in your plugin will help keep running server forever. Maybe a second process which monitoring the first, for example send syn tcp request on port and see if the server replies with an ack, if not maybe there is a way to terminate the server and reload it again. There is any?

Thanks for reporting the last update, I'm using VLAN as decoder in the sony  bravia Android TV , I dont' know if it does use some HW decoders which create the problem too.
Reporting the version in your window is useful to understand which version of your plugin is installed and if it's needed to update. I mean in the configuration window of your plugin, do you have the chance to write there the version number?
Thank you

**Comment by iamscottxu** [comment]
@Barabba11 

Even if you think that the log output does not contain any interesting information, the log output may be of great help in analyzing the problem.
In addition, please provide details of how to play in Android TV so that I can reproduce this problem.
Thank you.

**Comment by iamscottxu** [comment]
@Barabba11 

> Reporting the version in your window is useful to understand which version of your plugin is installed and if it's needed to update. I mean in the configuration window of your plugin, do you have the chance to write there the version number?

This suggestion is very good and will be added in a future version.
